name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        id: build-image
        run: |
          IMAGE_NAME=my-strapi-app
          IMAGE_TAG=${GITHUB_SHA:0:7}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          IMAGE_NAME=my-strapi-app
          IMAGE_TAG=${GITHUB_SHA:0:7}
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Set output for image tag
        run: echo "::set-output name=image_tag::${{ env.image_tag }}"