name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: roohmeiy
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="my-strapi-app"
          IMAGE_TAG="${GITHUB_SHA::7}"
          docker build -t roohmeiy/$IMAGE_NAME:$IMAGE_TAG .
          docker push roohmeiy/$IMAGE_NAME:$IMAGE_TAG

          # Create a text file with the IMAGE_TAG
          echo "$IMAGE_TAG" > image_tag.txt       

      - name: Check IMAGE_TAG file content 
        run: |
          cat image_tag.txt

      - name: Upload IMAGE_TAG artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag  
          path: image_tag.txt