name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/latest-image-tag.txt'
      - '.github/workflows/cd.yml'
      - '.github/workflows/ci.yml'

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="my-strapi-app"
          IMAGE_TAG="${GITHUB_SHA::7}"
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/$IMAGE_NAME:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_HUB_USER }}/$IMAGE_NAME:$IMAGE_TAG
          mkdir -p .github
          echo "$IMAGE_TAG" > .github/latest-image-tag.txt

      - name: Commit and push updated image tag
        run: |
          git config user.name "Payal"
          git config user.email "roohmeiy@gmail.com"
          git add .github/latest-image-tag.txt
          git commit -m "Update latest image tag [skip ci]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git push