name: Destroy infra

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Terraform Init
        working-directory: ./Terraform-blue-green-deployment
        run: terraform init
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Destroy
        working-directory: ./Terraform-blue-green-deployment
        run: |
              echo "Starting cleanup of resources..."
              terraform destroy -auto-approve
              echo "Cleanup completed"
        env:
              TF_VAR_ecr_repo_name: ${{ secrets.ECR_REPOSITORY_NAME }}
              TF_VAR_image_tag: ${{ github.sha }}
              TF_VAR_vpc_name: ${{ secrets.VPC_NAME }}
              TF_VAR_igw_name: ${{ secrets.IGW_NAME }}
              TF_VAR_security_group_name: ${{ secrets.SECURITY_GROUP_NAME }}
              TF_VAR_ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
              TF_VAR_task_definition_name: ${{ secrets.TASK_DEFINITION_NAME }}
              TF_VAR_ecs_service_name: ${{ secrets.ECS_SERVICE_NAME }}
              TF_VAR_alb_name: ${{ secrets.ALB_NAME }}
              TF_VAR_target_group_name: ${{ secrets.TARGET_GROUP_NAME }}
              TF_VAR_api_token_salt: ${{ secrets.API_TOKEN_SALT }}
              TF_VAR_admin_jwt_secret: ${{ secrets.ADMIN_JWT_SECRET }}
              TF_VAR_transfer_token_salt: ${{ secrets.TRANSFER_TOKEN_SALT }}
              TF_VAR_app_keys: ${{ secrets.APP_KEYS }}
              TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
              TF_VAR_alarm_email: ${{ secrets.ALARM_EMAIL }}