name: Deploy Strapi to AWS ECS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and push it to ECR
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        # Also tag as latest for convenience
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      id: init
      working-directory: ./Terraform-ecs-cicd
      run: terraform init
      env:
        TF_VAR_ecr_repo_name: ${{ secrets.ECR_REPOSITORY_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Plan
      id: plan
      working-directory: ./Terraform-ecs-cicd
      run: terraform plan -out=tfplan
      env:
        TF_VAR_ecr_repo_name: ${{ secrets.ECR_REPOSITORY_NAME }}
        TF_VAR_image_tag: ${{ github.sha }}
        TF_VAR_vpc_name: ${{ secrets.VPC_NAME }}
        TF_VAR_igw_name: ${{ secrets.IGW_NAME }}
        TF_VAR_security_group_name: ${{ secrets.SECURITY_GROUP_NAME }}
        TF_VAR_ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
        TF_VAR_task_definition_name: ${{ secrets.TASK_DEFINITION_NAME }}
        TF_VAR_ecs_service_name: ${{ secrets.ECS_SERVICE_NAME }}
        TF_VAR_alb_name: ${{ secrets.ALB_NAME }}
        TF_VAR_target_group_name: ${{ secrets.TARGET_GROUP_NAME }}
        TF_VAR_api_token_salt: ${{ secrets.API_TOKEN_SALT }}
        TF_VAR_admin_jwt_secret: ${{ secrets.ADMIN_JWT_SECRET }}
        TF_VAR_transfer_token_salt: ${{ secrets.TRANSFER_TOKEN_SALT }}
        TF_VAR_app_keys: ${{ secrets.APP_KEYS }}

    - name: Terraform Apply
      id: apply
      working-directory: ./Terraform-ecs-cicd
      run: terraform apply -auto-approve tfplan
      env:
        TF_VAR_ecr_repo_name: ${{ secrets.ECR_REPOSITORY_NAME }}
        TF_VAR_image_tag: ${{ github.sha }}
        TF_VAR_vpc_name: ${{ secrets.VPC_NAME }}
        TF_VAR_igw_name: ${{ secrets.IGW_NAME }}
        TF_VAR_security_group_name: ${{ secrets.SECURITY_GROUP_NAME }}
        TF_VAR_ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
        TF_VAR_task_definition_name: ${{ secrets.TASK_DEFINITION_NAME }}
        TF_VAR_ecs_service_name: ${{ secrets.ECS_SERVICE_NAME }}
        TF_VAR_alb_name: ${{ secrets.ALB_NAME }}
        TF_VAR_target_group_name: ${{ secrets.TARGET_GROUP_NAME }}
        TF_VAR_api_token_salt: ${{ secrets.API_TOKEN_SALT }}
        TF_VAR_admin_jwt_secret: ${{ secrets.ADMIN_JWT_SECRET }}
        TF_VAR_transfer_token_salt: ${{ secrets.TRANSFER_TOKEN_SALT }}
        TF_VAR_app_keys: ${{ secrets.APP_KEYS }}
      continue-on-error: true

    - name: Terraform Destroy on Failure
      if: steps.apply.outcome == 'failure'
      working-directory: ./Terraform-ecs-cicd
      run: terraform destroy -auto-approve
      env:
        TF_VAR_ecr_repo_name: ${{ secrets.ECR_REPOSITORY_NAME }}
        TF_VAR_image_tag: ${{ github.sha }}
        TF_VAR_vpc_name: ${{ secrets.VPC_NAME }}
        TF_VAR_igw_name: ${{ secrets.IGW_NAME }}
        TF_VAR_security_group_name: ${{ secrets.SECURITY_GROUP_NAME }}
        TF_VAR_ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
        TF_VAR_task_definition_name: ${{ secrets.TASK_DEFINITION_NAME }}
        TF_VAR_ecs_service_name: ${{ secrets.ECS_SERVICE_NAME }}
        TF_VAR_alb_name: ${{ secrets.ALB_NAME }}
        TF_VAR_target_group_name: ${{ secrets.TARGET_GROUP_NAME }}
        TF_VAR_api_token_salt: ${{ secrets.API_TOKEN_SALT }}
        TF_VAR_admin_jwt_secret: ${{ secrets.ADMIN_JWT_SECRET }}
        TF_VAR_transfer_token_salt: ${{ secrets.TRANSFER_TOKEN_SALT }}
        TF_VAR_app_keys: ${{ secrets.APP_KEYS }}

    - name: Check Terraform Apply Status and Exit on Failure
      if: steps.apply.outcome == 'failure'
      run: exit 1

    - name: Force new deployment
      if: steps.apply.outcome == 'success'
      run: |
        aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.ECS_SERVICE_NAME }} --force-new-deployment