name: Deploy Strapi to AWS ECS with Blue/Green

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/latest-image-tag.txt'
      - '.github/workflows/ci.yml'
      - '.github/workflows/cd.yml'
      - '.github/workflows/destroy.yml'
      - '.github/workflows/strapi-ecs.yml'
      - '.github/workflows/strapi-ecs-withcloudwatch.yml'

  workflow_dispatch:

env:
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build_image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        FULL_IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
        echo "Building Docker image: $FULL_IMAGE_URI"
        docker build -t $FULL_IMAGE_URI .
        docker push $FULL_IMAGE_URI
        echo "FULL_IMAGE_URI=${FULL_IMAGE_URI}" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.11.3

    - name: Terraform Init
      id: init
      working-directory: ./Terraform-blue-green-deployment
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_api_token_salt: ${{ secrets.API_TOKEN_SALT }}
        TF_VAR_admin_jwt_secret: ${{ secrets.ADMIN_JWT_SECRET }}
        TF_VAR_transfer_token_salt: ${{ secrets.TRANSFER_TOKEN_SALT }}
        TF_VAR_app_keys: ${{ secrets.APP_KEYS }}

    - name: Terraform Plan
      id: plan
      working-directory: ./Terraform-blue-green-deployment
      run: terraform plan -out=tfplan 
      env:
        TF_VAR_ecr_repo_name: ${{ env.ECR_REPOSITORY }}
        TF_VAR_image_tag: ${{ env.IMAGE_TAG }}
        TF_VAR_api_token_salt: ${{ secrets.API_TOKEN_SALT }}
        TF_VAR_admin_jwt_secret: ${{ secrets.ADMIN_JWT_SECRET }}
        TF_VAR_transfer_token_salt: ${{ secrets.TRANSFER_TOKEN_SALT }}
        TF_VAR_app_keys: ${{ secrets.APP_KEYS }}

    - name: Terraform Apply
      id: apply
      working-directory: ./Terraform-blue-green-deployment
      run: |
        terraform apply -auto-approve tfplan
      env:
        TF_VAR_ecr_repo_name: ${{ env.ECR_REPOSITORY }}
        TF_VAR_image_tag: ${{ env.IMAGE_TAG }}
        TF_VAR_api_token_salt: ${{ secrets.API_TOKEN_SALT }}
        TF_VAR_admin_jwt_secret: ${{ secrets.ADMIN_JWT_SECRET }}
        TF_VAR_transfer_token_salt: ${{ secrets.TRANSFER_TOKEN_SALT }}
        TF_VAR_app_keys: ${{ secrets.APP_KEYS }}

    - name: Register new task definition for CodeDeploy
      id: register_task_def
      run: |
        # Get current task definition
        TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ${{ secrets.TASK_DEFINITION_NAME }} --query 'taskDefinition' --output json)
        
        # Print debugging info
        echo "Using Docker image: '$FULL_IMAGE_URI'"
        
        # Update the task definition with the new image
        TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$FULL_IMAGE_URI" '.containerDefinitions[0].image = $IMAGE')        
        TASK_DEFINITION=$(echo $TASK_DEFINITION | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')        
        NEW_TASK_DEF=$(aws ecs register-task-definition --cli-input-json "$TASK_DEFINITION")        
        NEW_TASK_DEF_ARN=$(echo $NEW_TASK_DEF | jq -r '.taskDefinition.taskDefinitionArn')
        echo "NEW_TASK_DEF_ARN=${NEW_TASK_DEF_ARN}" >> $GITHUB_ENV

    - name: Create appspec.json file
      run: |
        echo '{
          "version": 0.0,
          "Resources": [
            {
              "TargetService": {
                "Type": "AWS::ECS::Service",
                "Properties": {
                  "TaskDefinition": "'"$NEW_TASK_DEF_ARN"'",
                  "LoadBalancerInfo": {
                    "ContainerName": "strapi-app",
                    "ContainerPort": 1337
                  },
                  "PlatformVersion": "LATEST"
                }
              }
            }
          ]
        }' > appspec.json

    - name: Upload AppSpec to S3
      run: |
        aws s3 cp appspec.json s3://${{ secrets.S3_BUCKET_NAME }}/appspec.json

    - name: Trigger CodeDeploy Deployment
      id: trigger_codedeploy
      run: |
        DEPLOYMENT_ID=$(aws deploy create-deployment \
          --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
          --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=JSON,key=appspec.json \
          --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes \
          --file-exists-behavior OVERWRITE \
          --query 'deploymentId' --output text)
        
        echo "Deployment ID: $DEPLOYMENT_ID"
        echo "DEPLOYMENT_ID=${DEPLOYMENT_ID}" >> $GITHUB_ENV

    - name: Wait for deployment to complete
      run: |
        echo "Waiting for deployment $DEPLOYMENT_ID to complete..."
        
        while true; do
          STATUS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query 'deploymentInfo.status' --output text)
          echo "Current deployment status: $STATUS"
          if [ "$STATUS" == "Succeeded" ]; then
            echo "Deployment completed successfully!"
            break
          elif [ "$STATUS" == "Failed" ]; then
            echo "Deployment failed with status: $STATUS"
            exit 1
          fi
          sleep 30
        done