name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove old container and deploy new one
        env:
          EC2_HOST: ${{ secrets.EC2_INSTANCE_PUBLIC_IP }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          IMAGE_NAME: my-strapi-app
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
        run: |
          # Create a temporary SSH key file
          echo "${EC2_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem

          # SSH into EC2 and remove the old container, then run the new one
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << EOF
            CONTAINER_NAME=my-strapi-app
            FULL_IMAGE_NAME=${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}

            # Stop and remove existing container if it exists
            if [ "\$(docker ps -q -f name=\$CONTAINER_NAME)" ]; then
              echo "Stopping and removing existing container..."
              docker stop \$CONTAINER_NAME
              docker rm \$CONTAINER_NAME
            fi

            # Pull the new image from Docker Hub
            echo "Pulling new image: \$FULL_IMAGE_NAME"
            docker pull \$FULL_IMAGE_NAME

            # Run the new container
            echo "Running new container..."
            docker run -d --name \$CONTAINER_NAME -p 1337:1337 \$FULL_IMAGE_NAME
          EOF
