name: CD Pipeline

on:
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Download IMAGE_TAG artifact
        uses: actions/download-artifact@v4  
        with:
          name: image-tag  

      - name: Set Environment Variable from IMAGE_TAG
        id: set-image-tag
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: roohmeiy
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Run commands on EC2 via SSH
        run: |
          IMAGE_NAME="my-strapi-app"
          IMAGE_TAG="${{ env.IMAGE_TAG }}"
          
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_INSTANCE_PUBLIC_IP }} << EOF
            # Export variables into the SSH session
            export IMAGE_NAME="$IMAGE_NAME"
            export IMAGE_TAG="$IMAGE_TAG"
            CONTAINER_NAME="my-strapi-app"

            # Stop and remove the existing container if it exists
            if [ "\$(docker ps -q -f name=\$CONTAINER_NAME)" ]; then
              echo "Stopping and removing existing container..."
              docker stop \$CONTAINER_NAME
              docker rm \$CONTAINER_NAME
            fi
            
            # Pull and run the Docker container
            docker pull roohmeiy/\$IMAGE_NAME:\$IMAGE_TAG
            docker run -d --name \$CONTAINER_NAME -p 1337:1337 roohmeiy/\$IMAGE_NAME:\$IMAGE_TAG      
          EOF