name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Run commands on EC2 via SSH
        run: |
          COMMANDS='
            #!/bin/bash
            set -e
            
            # Navigate to the Strapi application directory
            cd /home/ubuntu/strapi || exit
            
            # Check if the Strapi container already exists and remove it
            if [ "$(docker ps -aq -f name=strapi)" ]; then
              echo "Removing existing Strapi container..."
              docker rm -f strapi || true
            fi
            
            # Run the Strapi container in detached mode
            echo "Running Strapi container..."
            docker run -d \
              --name strapi \
              -p 1337:1337 \
              ${ secrets.AWS_ACCOUNT_ID }.dkr.ecr.${ secrets.AWS_REGION }.amazonaws.com/strapi:${{ github.event.inputs.image_tag }}
          '

          # Use SSH to execute the commands
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_INSTANCE_PUBLIC_IP }} "$COMMANDS"